### ISSUE TITLE
V3.0beta setup script

### ISSUE THREAD

**Issue by thomasinaz41213** [Lucifer06/RemoteGPIO#10]
When uninstalling, the setup script only appears to remove  /dev/gpio/relay_3 thru  /dev/gpio/relay_6 but not relay 7 and up. Also didn't see anywhere that the additional digital inputs were set to be removed. I know this is a work in progress. I just wanted to bring it to your attention.

**Comment by Lucifer06** [comment]
Thx good catch. Fixed in v3.0.7
