### ISSUE TITLE
missing file sets

### ISSUE THREAD

**Issue by kwindrem** [Lucifer06/RemoteGPIO#2]
RemoteGPIO packages do not contain .orig files that would otherwise allow SetupHelper create a missing file set if all the stock files match .orig files in another version. This requires a file set for each supported version and beta (release candidate) versions can come daily at times.

A missing file set error was recently posted to the Victron forum here:

https://community.victronenergy.com/questions/248146/remotegpio-no-file-set-for-v3207.html

Creating the .orig files is admittedly a large task as you need to build a database of files by Venus OS version then run a script to build the file sets for each package. The advantage of doing so is that the file sets are checked for consistency and errors flagged.

This is all described in Package development guidelines document here:

https://www.dropbox.com/scl/fo/bx5aftvgrqq0vp060mwip/h?rlkey=k28c2i49fjfpcyjfsuldwp159&dl=0

**Comment by Lucifer06** [comment]
Fixed in v3.0.x
