### ISSUE TITLE
All relays turn on/change state with no input from user

### ISSUE THREAD

**Issue by gwizzler** [Lucifer06/RemoteGPIO#37]
I've got a dingtian 8 relay board and I'm using modbus over rs485 with a usb to rs485 converter. I'm able to switch the relays on and off with some success but they seem to change their state on their own.

Is there anything I'm missing here? I'm happy to follow up with more information, cheers.

Using a cerbogx btw.

**Comment by drtinaz** [comment]
Are you using any relay logic in node red?

**Comment by gwizzler** [comment]
Nothing that I've done myself. It should be a stock installation.

**Comment by drtinaz** [comment]
You might try tcp to rule out a possible issue with the USB adapter.

**Comment by Lucifer06** [comment]
@gwizzler could you make sure you have no input link relay enabled (from the Dingtian web console).
