### ISSUE TITLE
setup script out of date

### ISSUE THREAD

**Issue by kwindrem** [Lucifer06/RemoteGPIO#42]
There have been recent changes to SetupHelper that cause failures in the setup script for RemoteGPIO as reported in https://github.com/kwindrem/SetupHelper/issues/97.

RemoteGPIO package should be updated with the new SetupHelper guidelines. Specifically, the call to helper resources should be updated to not look in the package directory (just SetupHelper's directory) and not look for a version file in the HelperResources directory.

**Comment by Lucifer06** [comment]
Hi Kevin, Thx for the heads-up. I will have a look in the coming days. Cheers,FreD. Excuse possible typo: swallowed by my iPhoneLe 8 sept. 2024 à 21:25, kwindrem ***@***.***> a écrit :﻿
There have been recent changes to SetupHelper that cause failures in the setup script for RemoteGPIO as reported in kwindrem/SetupHelper#97.
RemoteGPIO package should be updated with the new SetupHelper guidelines.

**Comment by kwindrem** [comment]
I updated SetupHelper to prevent the crash during setup so a change is optional.

The crash was because the helper files were looking for a version file but I recently deleted it. I put it back.
