### ISSUE TITLE
version number not consistent with Victron version scheme

### ISSUE THREAD

**Issue by kwindrem** [Lucifer06/RemoteGPIO#5]
I see you are using the traditional vX.Y.Z version format, however Victron is using vX.Y~Z where the `~Z` portion is for release versions. In that scheme, v1.2 is interpreted as later than `v1.2~5`

Right now, SetupHelper will interpret v1.2.1 as later than v1.2.0 but v1.2 will be the latest of the three.

I also detect versions like v2.3d1, v2.3.a1 v2.3b1 as development, alpha test and beta test, respectively and rank them in that order: v2.3b1 is the "newest". But v2.3 would be newer than all the others.

How would you indicate a prerelease version number? A released version (which must be identified as newer than a release).

I'm not sure I can accommodate vX.Y.ZbW format and still support Victron versioning. Right now, the .W portion would be ignored.

**Comment by Lucifer06** [comment]
Thx Kevin, good to know. I suppose you recommend we follow Victron's versioning rule?

**Comment by kwindrem** [comment]
Yes, it would be easiest to follow their rules but with some limitations, I can handle some variation.

The main limitation is only three numbers for major, minor and prelease and only two major, minor for a released build. Within that, I can accommodate your format as long as I know what to expect.

**Comment by Lucifer06** [comment]
OK I think I can accommodate to Victron rule. Excuse possible typo: swallowed by my iPhoneLe 21 déc. 2023 à 16:41, kwindrem ***@***.***> a écrit :﻿
Yes, it would be easiest to follow their rules but with some limitations, I can handle some variation.
The main limitation is only three numbers for major, minor and prelease and only two major, minor for a released build. Within that, I can accommodate your format as long as I know what to expect.

**Comment by kwindrem** [comment]
If you want to stick with v1.2.3, that's fine as long as you keep releases greater than test releases. That works now.

**Comment by Lucifer06** [comment]
👍Excuse possible typo: swallowed by my iPhoneLe 21 déc. 2023 à 17:16, kwindrem ***@***.***> a écrit :﻿
If you want to stick with v1.2.3, that's fine as long as you keep releases greater than test releases. That works now.
